import { SCORE_RULES } from "./score.mjs";

const CATEGORY_LABELS = Object.freeze({
  applications: "Applications",
  automation: "Automation",
  clients: "Clients and SDKs",
  guides: "Guides",
  monitoring: "Monitoring",
  testing: "Testing",
  verification: "Identity and verification",
});

export function escapeHtml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

export function escapeMarkdown(value) {
  return String(value)
    .replaceAll("\\", "\\\\")
    .replaceAll("|", "\\|")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;");
}

function categoryLabel(category) {
  return CATEGORY_LABELS[category] ?? category;
}

function checkedDate(report) {
  return report.generated_at.slice(0, 10);
}

function signalText(project) {
  const checks = project.readiness.checks;
  const labels = [];
  if (checks.find((check) => check.id === "ci")?.passed) labels.push("automation");
  if (checks.find((check) => check.id === "tests")?.passed) labels.push("tests");
  if (checks.find((check) => check.id === "security")?.passed) labels.push("security");
  if (checks.find((check) => check.id === "version")?.passed) labels.push("versioned");
  return labels.length ? labels.join(", ") : "limited evidence";
}

function scoreText(project) {
  return project.readiness.score === null ? "unscored" : `${project.readiness.score}/100`;
}

function projectUrl(repo) {
  return `https://github.com/${repo}`;
}

function safeObservedLink(value) {
  if (typeof value !== "string") return null;
  try {
    const parsed = new URL(value);
    return parsed.protocol === "https:" && parsed.hostname === "github.com" ? parsed.href : null;
  } catch {
    return null;
  }
}

export function renderReadme(report) {
  const rows = report.projects
    .map((project) => {
      const available = project.observation.available ? "observed" : "unavailable";
      return `| [${escapeMarkdown(project.repo)}](${projectUrl(project.repo)}) | ${escapeMarkdown(project.summary)} | ${escapeMarkdown(categoryLabel(project.category))} | ${project.readiness.grade} | ${scoreText(project)} | ${escapeMarkdown(signalText(project))} | ${available} |`;
    })
    .join("\n");

  return `# Technocore Verified Index

[![CI](https://github.com/hazzanzico/technocore-verified-index/actions/workflows/ci.yml/badge.svg)](https://github.com/hazzanzico/technocore-verified-index/actions/workflows/ci.yml)
[![Refresh](https://github.com/hazzanzico/technocore-verified-index/actions/workflows/refresh.yml/badge.svg)](https://github.com/hazzanzico/technocore-verified-index/actions/workflows/refresh.yml)

An evidence-first, automatically refreshed index of community projects built
around [FLOP Labs' Technocore Chat](https://github.com/flop-labs/technocore-chat).

> **Independent community project.** A listing or grade is not FLOP Labs
> endorsement, a security audit, contribution credit, or airdrop eligibility.

## What makes this different

- The source catalog is structured JSON rather than a hand-maintained link table.
- A dependency-free verifier reads observable GitHub metadata on a schedule.
- It never clones, installs, imports, or executes an indexed project's code.
- Every point is explained in [METHODOLOGY.md](METHODOLOGY.md).
- JSON, detailed Markdown, and a searchable static site come from one snapshot.
- The maintainer's own project receives the same rules as every other entry.

## Current index

Generated ${escapeMarkdown(report.generated_at)} from ${report.project_count} catalogued projects.
Projects are ordered by repository name, not score.

| Project | Purpose | Category | Grade | Readiness | Strong signals | API state |
|---|---|---|---:|---:|---|---|
${rows}

Read the [detailed report](reports/latest.md), download the
[machine-readable snapshot](reports/latest.json), or open the generated site in
<code>site/index.html</code>.

## Reading the score

The readiness score covers repository accessibility, archive state, license,
README, tests, latest completed automation, security policy, version markers,
declared protocol evidence, and recent activity. It does **not** inspect source
semantics or establish that a project is secure or protocol-correct.

| Grade | Score |
|---|---:|
| A | 85–100 |
| B | 70–84 |
| C | 50–69 |
| D | 0–49 |
| U | Unavailable and deliberately unscored |

## Reproduce

~~~console
npm ci
npm test
npm run refresh
~~~

<code>GITHUB_TOKEN</code> is optional locally and raises the GitHub API rate limit. Never
put a token in the catalog or a command-line URL.

## Contributing

See [CONTRIBUTING.md](CONTRIBUTING.md), [GOVERNANCE.md](GOVERNANCE.md), and
[SECURITY.md](SECURITY.md). Descriptions are reviewed by people; observable
facts and scores are regenerated by code.
`;
}

function detailValue(value) {
  if (value === null || value === undefined || value === "") return "not observed";
  if (typeof value === "boolean") return value ? "yes" : "no";
  return escapeMarkdown(value);
}

export function renderDetailedReport(report) {
  const projects = report.projects
    .map((project) => {
      const checks = project.readiness.checks
        .map(
          (check) =>
            `| ${escapeMarkdown(check.label)} | ${check.passed ? "pass" : "not observed"} | ${check.awarded}/${check.points} |`,
        )
        .join("\n");
      const runUrl = safeObservedLink(project.observation.automation.url);
      const run = runUrl ? `[${project.observation.automation.conclusion}](${runUrl})` : detailValue(project.observation.automation.conclusion);
      const warnings = project.observation.warnings.length
        ? project.observation.warnings.map(escapeMarkdown).join(", ")
        : "none";
      return `## [${escapeMarkdown(project.repo)}](${projectUrl(project.repo)}) — ${project.readiness.grade} (${scoreText(project)})

${escapeMarkdown(project.summary)}

- Category: ${escapeMarkdown(categoryLabel(project.category))}
- Platforms: ${project.platforms.map(escapeMarkdown).join(", ")}
- License: ${detailValue(project.observation.license)}
- Default branch: ${detailValue(project.observation.default_branch)}
- Last push: ${detailValue(project.observation.pushed_at)}
- Latest completed automation: ${run}
- Latest release: ${detailValue(project.observation.version.release)}
- Latest tag: ${detailValue(project.observation.version.tag)}
- Observation warnings: ${warnings}

| Check | Result | Points |
|---|---|---:|
${checks}
`;
    })
    .join("\n");
  return `# Technocore Verified Index — detailed report

Generated ${escapeMarkdown(report.generated_at)}. These are observable
repository-readiness signals, not security or protocol certifications. See
[METHODOLOGY.md](../METHODOLOGY.md) for exact boundaries.

${projects}`;
}

function renderCard(project) {
  const tags = project.tags
    .map((tag) => `<span class="tag">${escapeHtml(tag)}</span>`)
    .join("");
  const checks = project.readiness.checks
    .map(
      (check) =>
        `<li class="${check.passed ? "pass" : "miss"}"><span>${escapeHtml(check.label)}</span><strong>${check.awarded}/${check.points}</strong></li>`,
    )
    .join("");
  const searchable = [project.repo, project.summary, project.category, ...project.tags].join(" ").toLowerCase();
  const displayedScore = project.readiness.score === null ? "—" : project.readiness.score;
  return `<article class="card" data-category="${escapeHtml(project.category)}" data-grade="${project.readiness.grade}" data-search="${escapeHtml(searchable)}">
  <div class="score grade-${project.readiness.grade.toLowerCase()}"><strong>${displayedScore}</strong><span>Grade ${project.readiness.grade}</span></div>
  <div class="content">
    <p class="eyebrow">${escapeHtml(categoryLabel(project.category))}</p>
    <h2><a href="${projectUrl(project.repo)}" rel="noreferrer">${escapeHtml(project.repo)}</a></h2>
    <p>${escapeHtml(project.summary)}</p>
    <div class="tags">${tags}</div>
    <details><summary>Observable checks</summary><ul class="checks">${checks}</ul></details>
  </div>
</article>`;
}

export function renderHtml(report) {
  const categoryOptions = Object.entries(CATEGORY_LABELS)
    .map(([value, label]) => `<option value="${value}">${escapeHtml(label)}</option>`)
    .join("");
  const cards = report.projects.map(renderCard).join("\n");
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; img-src data:; base-uri 'none'; form-action 'none'">
  <title>Technocore Verified Index</title>
  <style>
    :root{color-scheme:dark;--bg:#090b10;--panel:#121722;--line:#273147;--text:#f3f6ff;--muted:#a7b1c5;--cyan:#5de4c7;--amber:#ffcc66;--red:#ff6b7a}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 15% -5%,#163040 0,transparent 34%),var(--bg);color:var(--text);font:16px/1.55 ui-sans-serif,system-ui,sans-serif}main{width:min(1100px,calc(100% - 32px));margin:auto;padding:72px 0}.kicker,.eyebrow{color:var(--cyan);font-size:.76rem;font-weight:800;letter-spacing:.13em;text-transform:uppercase}h1{font-size:clamp(2.4rem,7vw,5.4rem);line-height:.95;margin:.2em 0;max-width:900px}.intro{color:var(--muted);font-size:1.1rem;max-width:760px}.notice{border-left:3px solid var(--amber);padding:10px 16px;background:#ffcc6610;margin:28px 0}.controls{display:grid;grid-template-columns:2fr 1fr 1fr;gap:10px;margin:30px 0}input,select{width:100%;background:var(--panel);border:1px solid var(--line);border-radius:9px;color:var(--text);padding:12px;font:inherit}.meta{color:var(--muted);margin-bottom:18px}.grid{display:grid;gap:14px}.card{display:grid;grid-template-columns:115px 1fr;border:1px solid var(--line);border-radius:14px;background:#121722d9;overflow:hidden}.score{display:grid;place-content:center;text-align:center;border-right:1px solid var(--line)}.score strong{font-size:2.3rem}.score span{color:var(--muted);font-size:.8rem}.grade-a strong{color:var(--cyan)}.grade-b strong{color:#9ed072}.grade-c strong{color:var(--amber)}.grade-d strong{color:var(--red)}.grade-u strong{color:var(--muted)}.content{padding:20px 22px}.content h2{margin:.1rem 0}.content a{color:var(--text);text-decoration-color:var(--cyan);text-underline-offset:4px}.content p{color:var(--muted)}.tags{display:flex;flex-wrap:wrap;gap:7px}.tag{border:1px solid var(--line);border-radius:999px;padding:3px 9px;font-size:.78rem}.checks{padding:0;list-style:none}.checks li{display:flex;justify-content:space-between;border-bottom:1px solid var(--line);padding:6px 0}.pass strong{color:var(--cyan)}.miss{color:var(--muted)}footer{color:var(--muted);margin-top:42px;border-top:1px solid var(--line);padding-top:20px}footer a{color:var(--cyan)}[hidden]{display:none!important}@media(max-width:700px){main{padding:42px 0}.controls{grid-template-columns:1fr}.card{grid-template-columns:82px 1fr}.content{padding:16px}.score strong{font-size:1.8rem}}
  </style>
</head>
<body><main>
  <p class="kicker">Evidence over hype</p>
  <h1>Technocore Verified Index</h1>
  <p class="intro">A reproducible view of observable maintenance signals across community Technocore projects. No indexed code is cloned or executed.</p>
  <p class="notice"><strong>Independent community project.</strong> Scores are not security audits, FLOP Labs endorsements, contribution credit, or airdrop eligibility.</p>
  <section class="controls" aria-label="Project filters">
    <input id="search" type="search" placeholder="Search projects and capabilities" aria-label="Search projects">
    <select id="category" aria-label="Filter by category"><option value="">All categories</option>${categoryOptions}</select>
    <select id="grade" aria-label="Filter by grade"><option value="">All grades</option><option>A</option><option>B</option><option>C</option><option>D</option><option>U</option></select>
  </section>
  <p class="meta"><span id="count">${report.project_count}</span> projects · checked ${checkedDate(report)} · <a href="https://github.com/hazzanzico/technocore-verified-index/blob/main/reports/latest.json">JSON snapshot</a> · <a href="https://github.com/hazzanzico/technocore-verified-index/blob/main/METHODOLOGY.md">methodology</a></p>
  <section class="grid" id="projects">${cards}</section>
  <footer>Generated from a structured catalog. Project order is alphabetical, not ranked. Official Technocore source: <a href="https://github.com/flop-labs/technocore-chat">flop-labs/technocore-chat</a>.</footer>
</main>
<script>
const cards=[...document.querySelectorAll('.card')],search=document.querySelector('#search'),category=document.querySelector('#category'),grade=document.querySelector('#grade'),count=document.querySelector('#count');function filter(){const query=search.value.trim().toLowerCase();let shown=0;for(const card of cards){const visible=(!query||card.dataset.search.includes(query))&&(!category.value||card.dataset.category===category.value)&&(!grade.value||card.dataset.grade===grade.value);card.hidden=!visible;if(visible)shown++}count.textContent=shown}for(const control of [search,category,grade])control.addEventListener('input',filter);
</script></body></html>\n`;
}

export function serializeReport(report) {
  return `${JSON.stringify(report, null, 2)}\n`;
}

export function scoreRuleTotal() {
  return SCORE_RULES.reduce((total, rule) => total + rule.points, 0);
}
